source 'http://rubygems.org'

gem 'cucumber'
gem 'rspec'
gem 'rake'
gem 'page-object'
gem 'fig_newton'
gem 'require_all'
gem 'parallel_tests'
gem 'hub'
gem 'rest-client'
gem 'nokogiri'
gem 'gmail'
gem 'webdriver-user-agent'
gem 'watir'